version: '3'
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis-lock
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: